name: Unit Testing & Linting
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup PNPM v8
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Lint & Unit Test
        run: pnpm run lint && pnpm run test