name: Unit Testing & Linting

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18]
        pnpm-version: [8]
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup PNPM v8
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Linting
        run: pnpm run lint
        
      - name: Unit Testing
        run: pnpm run test

      - name: Build
        run: pnpm run build